# Generated by Django 4.2.29 on 2026-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='statut',
            field=models.CharField(choices=[('Publié', 'Publié'), ('Brouillon', 'Brouillon')], default='Brouillon', max_length=20),
        ),
    ]
